name: Deploy to Deta

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.2.0' 

    - name: Install dependencies
      run: npm install

    - name: Install Deta CLI
      run: curl -fsSL https://get.deta.dev/cli.sh | sh

    - name: Authenticate Deta CLI
      run: deta auth login
      env:
        DETA_TOKEN: ${{ secrets.DETA_TOKEN }}

    - name: Set environment variables
      run: echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" >> $GITHUB_ENV

    - name: Deploy to Deta
      run: deta deploy
